### PR TITLE
Closes #150 -Fixed capitalization of acronyms.

### LINKED ISSUE #150: Acronyms should be caps, not camel
golint insists that acronyms that are embedded in identifiers should be all caps and not camel cased. It is warning about HTTP, TLS, XSRF, etc., but does not seem to be aware of PEM, PBKDF2, and probably others.

### PR DESCRIPTION
**Pull request by geekthattweaks**
More golint complaining being fixed. This time technical acronyms not being all uppercase.

### CODE REVIEW

File: authentication/login_handler_test.go [hunk 1]
```diff
@@ -19,7 +19,7 @@ import (
 	"golang.org/x/net/html"
 )
 
-func getXsrfToken(n *html.Node, xsrfName string) (string, error) {
+func getXSRFToken(n *html.Node, xsrfName string) (string, error) {
```
Comment (proidiot) [inline authentication/login_handler_test.go]: Kind of surprised it isn't also complaining about `xsrfName` and `xsrfToken`, but either way is fine with me.

File: net/basictls_test.go [hunk 2]
```diff
@@ -13,19 +13,19 @@ import (
 	configutil "github.com/stuphlabs/pullcord/config/util"
 )
 
-func TestBasicTlsListenerType(t *testing.T) {
-	b := new(BasicTlsListener)
+func TestBasicTLSListenerType(t *testing.T) {
```
Comment (proidiot) [inline net/basictls_test.go]: Ah, of course! :+1:
